/*Under construction*/ 
<div class="loadingio-spinner-gear-0317r5vdemop"><div class="ldio-uns0kukznh">
<div><div></div><div></div><div></div><div></div><div></div><div></div></div>
</div></div>

<style type="text/css">
@keyframes ldio-uns0kukznh {
    0% { transform: rotate(0deg) }
   50% { transform: rotate(22.5deg) }
  100% { transform: rotate(45deg) }
}
.ldio-uns0kukznh > div {
  transform-origin: 100px 100px;
  animation: ldio-uns0kukznh 0.641025641025641s infinite linear;
}
.ldio-uns0kukznh > div div {
    position: absolute;
    width: 22px;
    height: 152px;
    background: #0a0a0a;
    left: 100px;
    top: 100px;
    transform: translate(-50%,-50%);
}
.ldio-uns0kukznh > div div:nth-child(1) {
    width: 120px;
    height: 120px;
    border-radius: 50%;
}
.ldio-uns0kukznh > div div:nth-child(6) {
    width: 80px;
    height: 80px;
    background: #f1f2f3;
    border-radius: 50%;
}.ldio-uns0kukznh > div div:nth-child(3) {
  transform: translate(-50%,-50%) rotate(45deg)
}.ldio-uns0kukznh > div div:nth-child(4) {
  transform: translate(-50%,-50%) rotate(90deg)
}.ldio-uns0kukznh > div div:nth-child(5) {
  transform: translate(-50%,-50%) rotate(135deg)
}
.loadingio-spinner-gear-0317r5vdemop {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #f1f2f3;
}
.ldio-uns0kukznh {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-uns0kukznh div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>